# Generated by Django 5.1.2 on 2024-10-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to='players.playerprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='qualifiers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='qualifiers',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers_player_1', to='players.playerprofile'),
        ),
        migrations.AddField(
            model_name='qualifiers',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers_player_2', to='players.playerprofile'),
        ),
        migrations.AddField(
            model_name='qualifiers',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers_matches', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='qualifiers',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers_winner', to='players.playerprofile'),
        ),
    ]
