# Generated by Django 5.1.2 on 2024-11-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('playoff', '0005_match_points_distributed'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='description',
        ),
        migrations.RemoveField(
            model_name='break',
            name='tournament',
        ),
        migrations.AddField(
            model_name='break',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='playoff.match'),
        ),
        migrations.AddField(
            model_name='break',
            name='qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='groups.qualifiers'),
        ),
        migrations.AlterField(
            model_name='break',
            name='points',
            field=models.IntegerField(),
        ),
    ]
