# Generated by Django 5.1.2 on 2024-12-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_break_description_remove_break_tournament_and_more'),
        ('tournaments', '0006_tournament_previous_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='tournaments.tournament'),
            preserve_default=False,
        ),
    ]
