# Generated by Django 5.1.2 on 2024-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('tournaments', '0002_remove_participant_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournament', to='players.playerprofile'),
        ),
    ]
