# Generated by Django 5.1.2 on 2024-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(default=16),
        ),
    ]
