# Generated by Django 5.1.2 on 2024-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff', '0002_remove_match_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='size',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
